# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
defaults: &defaults
  mailchimp_key: <%= ENV['MAILCHIMP_KEY'] %>
  mailchimp_list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  mailchimp_interest_ids: <%= ENV['MAILCHIMP_INTEREST_IDS'] %>

development:
  <<: *defaults
  secret_key_base: 41bbd9ada127c211dce86f0dfa0f47a5cf2264e47269b0b05fd36498036103bea7906df3f28b301002816c1999a011e616375ae84c455488bd40ab6f34ab64bc
  client_id: tuewgyQ5Gprq6WvZhU
  http_host: '5e4001e0.ngrok.io'

test:
  <<: *defaults
  secret_key_base: 5959eb4f529f82543a34dcd406afe49efe3ac8ac1756ed693938740d9e2475129f12c5502dc07099450f106dfeefc7bc87804ce18de8a877a84764c4c57f9fcc
  client_id: tuewgyQ5Gprq6WvZhU
  http_host: '5e4001e0.ngrok.io'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  client_id: <%= ENV['BITBUCKET_CLIENT_ID'] %>
  http_host: <%= ENV['HEROKU_APP_NAME'] %>.herokuapp.com
  logentries_token: <%= ENV['LOGENTRIES_TOKEN'] %>
